const users = [
  {
    id: 1,
    profilePic: "https://randomuser.me/api/portraits/men/1.jpg",
    name: "John Doe",
    role: "Boat owner",
    phone: "123-456-7890",
    email: "john.doe@example.com",
  },
  {
    id: 2,
    profilePic: "https://randomuser.me/api/portraits/women/1.jpg",
    name: "Jane Smith",
    role: "user",
    phone: "234-567-8901",
    email: "jane.smith@example.com",
  },
  {
    id: 3,
    profilePic: "https://randomuser.me/api/portraits/men/2.jpg",
    name: "Mike Johnson",
    role: "Boat owner",
    phone: "345-678-9012",
    email: "mike.johnson@example.com",
  },
  {
    id: 4,
    profilePic: "https://randomuser.me/api/portraits/women/2.jpg",
    name: "Emily Davis",
    role: "user",
    phone: "456-789-0123",
    email: "emily.davis@example.com",
  },
  {
    id: 5,
    profilePic: "https://randomuser.me/api/portraits/men/3.jpg",
    name: "Chris Brown",
    role: "Boat owner",
    phone: "567-890-1234",
    email: "chris.brown@example.com",
  },
  {
    id: 6,
    profilePic: "https://randomuser.me/api/portraits/women/3.jpg",
    name: "Sarah Wilson",
    role: "user",
    phone: "678-901-2345",
    email: "sarah.wilson@example.com",
  },
  {
    id: 7,
    profilePic: "https://randomuser.me/api/portraits/men/4.jpg",
    name: "David Lee",
    role: "Boat owner",
    phone: "789-012-3456",
    email: "david.lee@example.com",
  },
  {
    id: 8,
    profilePic: "https://randomuser.me/api/portraits/women/4.jpg",
    name: "Laura Martinez",
    role: "user",
    phone: "890-123-4567",
    email: "laura.martinez@example.com",
  },
  {
    id: 9,
    profilePic: "https://randomuser.me/api/portraits/men/5.jpg",
    name: "James Anderson",
    role: "Boat owner",
    phone: "901-234-5678",
    email: "james.anderson@example.com",
  },
  {
    id: 10,
    profilePic: "https://randomuser.me/api/portraits/women/5.jpg",
    name: "Olivia Thomas",
    role: "user",
    phone: "012-345-6789",
    email: "olivia.thomas@example.com",
  },
  {
    id: 11,
    profilePic: "https://randomuser.me/api/portraits/men/6.jpg",
    name: "Robert Jackson",
    role: "Boat owner",
    phone: "123-456-7890",
    email: "robert.jackson@example.com",
  },
  {
    id: 12,
    profilePic: "https://randomuser.me/api/portraits/women/6.jpg",
    name: "Sophia White",
    role: "user",
    phone: "234-567-8901",
    email: "sophia.white@example.com",
  },
  {
    id: 13,
    profilePic: "https://randomuser.me/api/portraits/men/7.jpg",
    name: "William Harris",
    role: "Boat owner",
    phone: "345-678-9012",
    email: "william.harris@example.com",
  },
  {
    id: 14,
    profilePic: "https://randomuser.me/api/portraits/women/7.jpg",
    name: "Isabella Clark",
    role: "user",
    phone: "456-789-0123",
    email: "isabella.clark@example.com",
  },
  {
    id: 15,
    profilePic: "https://randomuser.me/api/portraits/men/8.jpg",
    name: "Michael Lewis",
    role: "Boat owner",
    phone: "567-890-1234",
    email: "michael.lewis@example.com",
  },
];

export default users;